USE STG_ADVWORKS;
CREATE TABLE SALES.DM_ADDRESS (
    NK_ADDRESS INT NOT NULL,
    DS_ADDRESS NVARCHAR(255) NOT NULL,
    DS_CITY NVARCHAR(255) NOT NULL,
    DS_STATE NVARCHAR(50) NOT NULL,
    SG_STATE NVARCHAR(10) NOT NULL,
    DS_COUNTRY NVARCHAR(50) NOT NULL,
    DT_UPDATE_A DATETIME NOT NULL,
    DT_UPDATE_SP DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SALES.DEL_DM_ADDRESS') 
           AND [TYPE] IN (N'U'))
BEGIN
   DROP TABLE SALES.DEL_DM_ADDRESS;
END

CREATE TABLE SALES.DEL_DM_ADDRESS (
				NK_ADDRESS INT NOT NULL
)

USE DW_ADVWORKS;
CREATE TABLE SALES.DM_ADDRESS (
    SK_ADDRESS NUMERIC(10) IDENTITY(1,1) NOT NULL,
    NK_ADDRESS INT NOT NULL,
    DS_ADDRESS NVARCHAR(255) NOT NULL,
    DS_CITY NVARCHAR(255) NOT NULL,
    DS_STATE NVARCHAR(50) NOT NULL,
    SG_STATE NVARCHAR(10) NOT NULL,
    DS_COUNTRY NVARCHAR(50) NOT NULL,
    DT_UPDATE_A DATETIME NOT NULL,
    DT_UPDATE_SP DATETIME NOT NULL,
	DT_UPDATE DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL,
	CONSTRAINT DMADRPK PRIMARY KEY (SK_ADDRESS)
);

SELECT	-1					NK_ADDRESS, 
		'NO ADDRESS'		DS_ADDRESS, 
		'NO CITY'			DS_CITY, 
		'NO STATE'			DS_STATE,
		'NO STATE COD' 		SG_STATE, 
		'NO COUNTRY' 		DS_COUNTRY,
		GETDATE()			DT_UPDATE_A,
		GETDATE()			DT_UPDATE_SP,
		GETDATE()			DT_CARGA
UNION ALL
SELECT	ADDRESSID			NK_ADDRESS, 
		ADDRESSLINE1		DS_ADDRESS, 
		CITY				DS_CITY, 
		SP.NAME				DS_STATE,
		STATEPROVINCECODE	SG_STATE, 
		COUNTRYREGIONCODE	DS_COUNTRY,
		A.MODIFIEDDATE		DT_UPDATE_A,
		SP.MODIFIEDDATE		DT_UPDATE_SP,
		GETDATE()			DT_CARGA
FROM	PERSON.ADDRESS A
		LEFT JOIN PERSON.STATEPROVINCE SP ON A.STATEPROVINCEID = SP.STATEPROVINCEID
WHERE	1=1		
--		AND	CONVERT(DATE,C.MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)


MERGE DW_ADVWORKS.SALES.DM_ADDRESS DEST
USING STG_ADVWORKS.SALES.DM_ADDRESS UPD ON UPD.NK_ADDRESS = DEST.NK_ADDRESS
WHEN NOT MATCHED THEN INSERT
VALUES (
NK_ADDRESS, 
DS_ADDRESS, 
DS_CITY, 
DS_STATE,
SG_STATE, 
DS_COUNTRY,
DT_UPDATE_A,
DT_UPDATE_SP,
NULL, --UPD.DT_UPDATE
NULL, --UPD.DT_DELETE
UPD.DT_CARGA
) WHEN MATCHED AND
CONCAT(
UPD.DS_ADDRESS, 
UPD.DS_CITY, 
UPD.DS_STATE,
UPD.SG_STATE, 
UPD.DS_COUNTRY,
UPD.DT_UPDATE_A,
UPD.DT_UPDATE_SP,
UPD.DT_DELETE,
UPD.DT_CARGA
) <>
CONCAT(
UPD.DS_ADDRESS, 
UPD.DS_CITY, 
UPD.DS_STATE,
UPD.SG_STATE, 
UPD.DS_COUNTRY,
UPD.DT_UPDATE_A,
UPD.DT_UPDATE_SP,
UPD.DT_DELETE,
UPD.DT_CARGA
)
THEN
UPDATE
SET 
DEST.DS_ADDRESS				= UPD.DS_ADDRESS,		
DEST.DS_CITY 				= UPD.DS_CITY, 		
DEST.DS_STATE				= UPD.DS_STATE,		
DEST.SG_STATE 				= UPD.SG_STATE, 		
DEST.DS_COUNTRY				= UPD.DS_COUNTRY,		
DEST.DT_UPDATE_A			= UPD.DT_UPDATE_A,	
DEST.DT_UPDATE_SP			= UPD.DT_UPDATE_SP,	
DEST.DT_UPDATE				= GETDATE(),
DEST.DT_DELETE				= UPD.DT_DELETE,
DEST.DT_CARGA				= UPD.DT_CARGA;

SELECT	ADDRESSID			NK_ADDRESS
FROM	PERSON.ADDRESS A
WHERE	1=1		
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

UPDATE		DEST
SET			DEST.DT_DELETE = GETDATE()
FROM		DW_ADVWORKS.SALES.DM_ADDRESS DEST
LEFT JOIN	STG_ADVWORKS.SALES.DEL_DM_ADDRESS DEL ON DEL.NK_ADDRESS = DEST.NK_ADDRESS
WHERE		DEL.NK_ADDRESS IS NULL
AND			DEST.DT_DELETE IS NULL;

DROP TABLE STG_ADVWORKS.SALES.DEL_DM_ADDRESS