USE STG_ADVWORKS;
DROP TABLE SALES.DM_PRODUCT
USE DW_ADVWORKS;
DROP TABLE SALES.DM_PRODUCT

USE STG_ADVWORKS;
CREATE TABLE SALES.DM_PRODUCT (
    NK_PRODUCT INT NOT NULL,
    DS_PRODUCT NVARCHAR(255) NOT NULL,
    DS_COLOR NVARCHAR(50) NOT NULL,
    VL_STDCOST DECIMAL(18,2) NOT NULL,
    VL_SLGPRICE DECIMAL(18,2) NOT NULL,
    DS_SIZE NVARCHAR(50) NOT NULL,
    NR_DAYSMANUFACTURE INT NOT NULL,
    DS_PRODUCTLINE NVARCHAR(255) NOT NULL, 
    DT_SELLSTART NUMERIC(8) NOT NULL,
    DT_SELLEND NUMERIC(8) NOT NULL, 
    DT_DISCONTINUED NUMERIC(8) NOT NULL, 
    DT_REGUPDATE DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SALES.DEL_DM_PRODUCT') 
           AND [TYPE] IN (N'U'))
BEGIN
   DROP TABLE SALES.DEL_DM_PRODUCT;
END

CREATE TABLE SALES.DEL_DM_PRODUCT (
				NK_PRODUCT INT NOT NULL
)

USE DW_ADVWORKS;
CREATE TABLE SALES.DM_PRODUCT (
	SK_PRODUCT NUMERIC(10) IDENTITY(1,1) NOT NULL ,
    NK_PRODUCT INT NOT NULL,
    DS_PRODUCT NVARCHAR(255) NOT NULL,
    DS_COLOR NVARCHAR(50) NOT NULL, 
    VL_STDCOST DECIMAL(18,2) NOT NULL,
    VL_SLGPRICE DECIMAL(18,2) NOT NULL,
    DS_SIZE NVARCHAR(50) NOT NULL, 
    NR_DAYSMANUFACTURE INT NOT NULL,
    DS_PRODUCTLINE NVARCHAR(255) NOT NULL, 
    DT_SELLSTART NUMERIC(8) NOT NULL,
    DT_SELLEND NUMERIC(8),
    DT_DISCONTINUED NUMERIC(8), 
    DT_REGUPDATE DATE NOT NULL,
    DT_UPDATE DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL,
	CONSTRAINT DMPRODPK PRIMARY KEY (SK_PRODUCT)
);

SELECT	-1						NK_PRODUCT,
		'NO PRODUCT'			DS_PRODUCT,
		'NO COLOR'				DS_COLOR,
		0.00					VL_STDCOST,
		0.00					VL_SLGPRICE,
		'NO SIZE'				DS_SIZE,
		0						NR_DAYSMANUFACTURE,
		'NO PRODUCT LINE'		DS_PRODUCTLINE,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,GETDATE())),':-/ ','____'),'_','')) DT_SELLSTART,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,GETDATE())),':-/ ','____'),'_','')) DT_SELLEND,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,GETDATE())),':-/ ','____'),'_','')) DT_DISCONTINUED,
		GETDATE()				DT_REGUPDATE,
		GETDATE()				DT_CARGA
UNION ALL
SELECT	P.PRODUCTID				NK_PRODUCT,
		P.NAME					DS_PRODUCT,
		CASE WHEN P.COLOR IS NOT NULL THEN P.COLOR ELSE CASE WHEN P.NAME LIKE '% BLUE%' THEN 'BLUE' ELSE CASE WHEN P.NAME LIKE '% RED%' THEN 'RED' ELSE CASE WHEN P.NAME LIKE '% SILVER%' THEN 'SILVER' ELSE CASE WHEN P.NAME LIKE '% YELLOW%' THEN 'YELLOW' ELSE CASE WHEN P.NAME LIKE '% BLACK%' THEN 'BLACK' ELSE 'STANDARD' END END END END END END DS_COLOR,
		P.STANDARDCOST			VL_STDCOST,
		P.LISTPRICE				VL_SLGPRICE,
		CASE WHEN P.SIZE IS NULL THEN 'STANDARD' ELSE P.SIZE END DS_SIZE,
		P.DAYSTOMANUFACTURE		NR_DAYSMANUFACTURE,
		CASE WHEN P.PRODUCTLINE IS NOT NULL THEN P.PRODUCTLINE ELSE CASE WHEN P.PRODUCTLINE = 'R' THEN 'ROAD' ELSE CASE WHEN P.PRODUCTLINE = 'M' THEN 'MOUNTAIN'	ELSE CASE WHEN P.PRODUCTLINE = 'T' THEN 'TOURING' ELSE 'STANDARD' END END END END DS_PRODUCTLINE,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,SELLSTARTDATE)),':-/ ','____'),'_',''))			DT_SELLSTART,
		CASE WHEN SELLENDDATE IS NULL THEN -1 ELSE CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,SELLENDDATE)),':-/ ','____'),'_','')) END DT_SELLEND,
		CASE WHEN DISCONTINUEDDATE IS NULL THEN -1 ELSE CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,DISCONTINUEDDATE)),':-/ ','____'),'_','')) END DT_DISCONTINUED,
		P.MODIFIEDDATE			DT_REGUPDATE,
		GETDATE()				DT_CARGA
FROM	PRODUCTION.PRODUCT P
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

MERGE DW_ADVWORKS.SALES.DM_PRODUCT DEST
USING STG_ADVWORKS.SALES.DM_PRODUCT UPD ON UPD.NK_PRODUCT = DEST.NK_PRODUCT
WHEN NOT MATCHED THEN INSERT
VALUES (
UPD.NK_PRODUCT,
UPD.DS_PRODUCT,
UPD.DS_COLOR,
UPD.VL_STDCOST,
UPD.VL_SLGPRICE,
UPD.DS_SIZE,
UPD.NR_DAYSMANUFACTURE,
UPD.DS_PRODUCTLINE,
UPD.DT_SELLSTART,
UPD.DT_SELLEND,
UPD.DT_DISCONTINUED,
UPD.DT_REGUPDATE,
NULL, --UPD.DT_UPDATE
NULL, --UPD.DT_DELETE
UPD.DT_CARGA
)
WHEN MATCHED AND 
CONCAT(
UPD.DS_PRODUCT,
UPD.DS_COLOR,
UPD.VL_STDCOST,
UPD.VL_SLGPRICE,
UPD.DS_SIZE,
UPD.NR_DAYSMANUFACTURE,
UPD.DS_PRODUCTLINE,
UPD.DT_SELLSTART,
UPD.DT_SELLEND,
UPD.DT_DISCONTINUED,
UPD.DT_REGUPDATE,
UPD.DT_DELETE,
UPD.DT_CARGA
) <>
CONCAT(
DEST.DS_PRODUCT,
DEST.DS_COLOR,
DEST.VL_STDCOST,
DEST.VL_SLGPRICE,
DEST.DS_SIZE,
DEST.NR_DAYSMANUFACTURE,
DEST.DS_PRODUCTLINE,
DEST.DT_SELLSTART,
DEST.DT_SELLEND,
DEST.DT_DISCONTINUED,
DEST.DT_REGUPDATE,
DEST.DT_DELETE,
DEST.DT_CARGA
) 
THEN
UPDATE
SET 
DEST.DS_PRODUCT				=  UPD.DS_PRODUCT,
DEST.DS_COLOR				=  UPD.DS_COLOR,
DEST.VL_STDCOST				=  UPD.VL_STDCOST,
DEST.VL_SLGPRICE			=  UPD.VL_SLGPRICE,
DEST.DS_SIZE				=  UPD.DS_SIZE,
DEST.NR_DAYSMANUFACTURE		=  UPD.NR_DAYSMANUFACTURE,
DEST.DS_PRODUCTLINE			=  UPD.DS_PRODUCTLINE,
DEST.DT_SELLSTART			=  UPD.DT_SELLSTART,
DEST.DT_SELLEND				=  UPD.DT_SELLEND,
DEST.DT_DISCONTINUED		=  UPD.DT_DISCONTINUED,
DEST.DT_REGUPDATE			=  UPD.DT_REGUPDATE,
DEST.DT_UPDATE				= GETDATE(),
DEST.DT_DELETE				= UPD.DT_DELETE,
DEST.DT_CARGA				= UPD.DT_CARGA;

SELECT	P.PRODUCTID				NK_PRODUCT
FROM	PRODUCTION.PRODUCT P
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

UPDATE		DEST
SET			DEST.DT_DELETE = GETDATE()
FROM		DW_ADVWORKS.SALES.DM_PRODUCT DEST
LEFT JOIN	STG_ADVWORKS.SALES.DEL_DM_PRODUCT DEL ON DEL.NK_PRODUCT = DEST.NK_PRODUCT
WHERE		DEL.NK_PRODUCT IS NULL
AND			DEST.DT_DELETE IS NULL;

DROP TABLE STG_ADVWORKS.SALES.DEL_DM_PRODUCT
