USE STG_ADVWORKS;
CREATE TABLE SALES.DM_PRODUCT_CATEGORY (
    NK_SUBCATEGORY INT NOT NULL,
    DS_SUBCATEGORY NVARCHAR(255) NOT NULL,
    ID_CATEGORY INT NOT NULL,
    DS_CATEGORY NVARCHAR(255) NOT NULL,
    DT_REGUPDATE_PS DATE NOT NULL,
    DT_REGUPDATE_PC DATE NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SALES.DEL_DM_PRODUCT_CATEGORY') 
           AND [TYPE] IN (N'U'))
BEGIN
   DROP TABLE SALES.DEL_DM_PRODUCT_CATEGORY;
END

CREATE TABLE SALES.DEL_DM_PRODUCT_CATEGORY (
				NK_SUBCATEGORY INT NOT NULL
)

USE DW_ADVWORKS;
CREATE TABLE SALES.DM_PRODUCT_CATEGORY (
	SK_SUBCATEGORY NUMERIC(10) IDENTITY(1,1) NOT NULL,
    NK_SUBCATEGORY INT NOT NULL,
    DS_SUBCATEGORY NVARCHAR(255) NOT NULL,
    ID_CATEGORY INT NOT NULL,
    DS_CATEGORY NVARCHAR(255) NOT NULL,
    DT_REGUPDATE_PS DATE NOT NULL,
    DT_REGUPDATE_PC DATE NOT NULL,
	DT_UPDATE DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL,
	CONSTRAINT DM_PROCPK PRIMARY KEY (SK_SUBCATEGORY)
);

SELECT	-1						NK_SUBCATEGORY,
		'NO SUBCATEGORY NAME'	DS_SUBCATEGORY,
		-1						ID_CATEGORY,
		'NO CATEGORY NAME'		DS_CATEGORY,
		GETDATE()				DT_REGUPDATE_PS,
		GETDATE()				DT_REGUPDATE_PC,
		GETDATE()				DT_CARGA
UNION ALL
SELECT	PS.PRODUCTSUBCATEGORYID	NK_SUBCATEGORY,
		PS.NAME					DS_SUBCATEGORY,
		PC.PRODUCTCATEGORYID	ID_CATEGORY,
		PC.NAME					DS_CATEGORY,
		PS.MODIFIEDDATE			DT_REGUPDATE_PS,
		PC.MODIFIEDDATE			DT_REGUPDATE_PC,
		GETDATE()				DT_CARGA
FROM	PRODUCTION.PRODUCTSUBCATEGORY PS
		LEFT JOIN PRODUCTION.PRODUCTCATEGORY PC ON PS.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

MERGE DW_ADVWORKS.SALES.DM_PRODUCT_CATEGORY DEST
USING STG_ADVWORKS.SALES.DM_PRODUCT_CATEGORY UPD ON UPD.NK_SUBCATEGORY = DEST.NK_SUBCATEGORY
WHEN NOT MATCHED THEN INSERT
VALUES (
UPD.NK_SUBCATEGORY,
UPD.DS_SUBCATEGORY,
UPD.ID_CATEGORY,
UPD.DS_CATEGORY,
UPD.DT_REGUPDATE_PS,
UPD.DT_REGUPDATE_PC,
NULL, --UPD.DT_UPDATE
NULL, --UPD.DT_DELETE
UPD.DT_CARGA
)
WHEN MATCHED AND 
CONCAT(
UPD.DS_SUBCATEGORY,
UPD.ID_CATEGORY,
UPD.DS_CATEGORY,
UPD.DT_REGUPDATE_PS,
UPD.DT_REGUPDATE_PC,
UPD.DT_DELETE,
UPD.DT_CARGA
) <>
CONCAT(
DEST.DS_SUBCATEGORY,
DEST.ID_CATEGORY,
DEST.DS_CATEGORY,
DEST.DT_REGUPDATE_PS,
DEST.DT_REGUPDATE_PC,
DEST.DT_DELETE,
DEST.DT_CARGA
) 
THEN
UPDATE
SET 
DEST.DS_SUBCATEGORY			= UPD.DS_SUBCATEGORY,			
DEST.ID_CATEGORY			= UPD.ID_CATEGORY,
DEST.DS_CATEGORY			= UPD.DS_CATEGORY,
DEST.DT_REGUPDATE_PS		= UPD.DT_REGUPDATE_PS,
DEST.DT_REGUPDATE_PC		= UPD.DT_REGUPDATE_PC,
DEST.DT_UPDATE				= GETDATE(),
DEST.DT_DELETE				= UPD.DT_DELETE,
DEST.DT_CARGA				= UPD.DT_CARGA;

SELECT	PS.PRODUCTSUBCATEGORYID	NK_SUBCATEGORY
FROM	PRODUCTION.PRODUCTSUBCATEGORY PS
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

UPDATE		DEST
SET			DEST.DT_DELETE = GETDATE()
FROM		DW_ADVWORKS.SALES.DM_PRODUCT_CATEGORY DEST
LEFT JOIN	STG_ADVWORKS.SALES.DEL_DM_PRODUCT_CATEGORY DEL ON DEL.NK_SUBCATEGORY = DEST.NK_SUBCATEGORY
WHERE		DEL.NK_SUBCATEGORY IS NULL
AND			DEST.DT_DELETE IS NULL;

DROP TABLE STG_ADVWORKS.SALES.DEL_DM_PRODUCT_CATEGORY