USE STG_ADVWORKS;
CREATE TABLE SALES.DM_PROMOTION (
    NK_PROMOTION INT NOT NULL,
    DS_PROMOTION NVARCHAR(255) NOT NULL,
    RL_DISCOUNT DECIMAL(18,2) NOT NULL,
    DS_TYPE NVARCHAR(50) NOT NULL,
    NR_MINQT INT NOT NULL,
    NR_MAXQT INT NOT NULL,
    DT_START NUMERIC(8) NOT NULL,
    DT_END NUMERIC(8) NOT NULL,
	DT_REGUPDATE DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

IF EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'SALES.DEL_DM_PROMOTION') 
           AND [type] IN (N'U'))
BEGIN
   DROP TABLE SALES.DEL_DM_PROMOTION;
END

CREATE TABLE SALES.DEL_DM_PROMOTION (
				NK_PROMOTION INT NOT NULL
)


USE DW_ADVWORKS;
CREATE TABLE SALES.DM_PROMOTION (
	SK_PROMOTION NUMERIC(10) IDENTITY(1,1) NOT NULL,
    NK_PROMOTION INT NOT NULL,
    DS_PROMOTION NVARCHAR(255) NOT NULL,
    RL_DISCOUNT DECIMAL(18,2) NOT NULL,
    DS_TYPE NVARCHAR(50) NOT NULL,
    NR_MINQT INT NOT NULL,
    NR_MAXQT INT NOT NULL,
    DT_START NUMERIC(8) NOT NULL,
    DT_END NUMERIC(8) NOT NULL,
	DT_REGUPDATE DATETIME NOT NULL,
    DT_UPDATE DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL,
	CONSTRAINT DMPROMPK PRIMARY KEY (SK_PROMOTION)
);

SELECT	-1								NK_PROMOTION,
		'NO PROMOTION'					DS_PROMOTION,
		0.00							RL_DISCOUNT,
		'NO TYPE'						DS_TYPE,
		0								NR_MINQT,
		0								NR_MAXQT,
		GETDATE()						DT_REGUPDATE,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,GETDATE())),':-/ ','____'),'_',''))					DT_START,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,GETDATE())),':-/ ','____'),'_',''))					DT_END,
		GETDATE()						DT_CARGA
UNION ALL
SELECT	SPECIALOFFERID					NK_PROMOTION,
		DESCRIPTION						DS_PROMOTION,
		DISCOUNTPCT						RL_DISCOUNT,
		TYPE							DS_TYPE,
		MINQTY							NR_MINQT,
		IIF(MAXQTY IS NULL, 0, MAXQTY)	NR_MAXQT,
		MODIFIEDDATE					DT_REGUPDATE,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,STARTDATE)),':-/ ','____'),'_','')) DT_START,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,ENDDATE)),':-/ ','____'),'_',''))	DT_END,
		GETDATE()						DT_CARGA
FROM	SALES.SPECIALOFFER SO
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

MERGE DW_ADVWORKS.SALES.DM_PROMOTION DEST
USING STG_ADVWORKS.SALES.DM_PROMOTION UPD ON UPD.NK_PROMOTION = DEST.NK_PROMOTION
WHEN NOT MATCHED THEN INSERT
VALUES (
UPD.NK_PROMOTION,
UPD.DS_PROMOTION,
UPD.RL_DISCOUNT,
UPD.DS_TYPE,
UPD.NR_MINQT,
UPD.NR_MAXQT,
UPD.DT_START,
UPD.DT_END,
DT_REGUPDATE,
NULL, --UPD.DT_UPDATE
NULL, --UPD.DT_DELETE
UPD.DT_CARGA
)
WHEN MATCHED AND 
CONCAT(
UPD.DS_PROMOTION,
UPD.RL_DISCOUNT,
UPD.DS_TYPE,
UPD.NR_MINQT,
UPD.NR_MAXQT,
UPD.DT_START,
UPD.DT_END,
UPD.DT_REGUPDATE,
UPD.DT_DELETE,
UPD.DT_CARGA
) <>
CONCAT(
DEST.DS_PROMOTION,
DEST.RL_DISCOUNT,
DEST.DS_TYPE,
DEST.NR_MINQT,
DEST.NR_MAXQT,
DEST.DT_START,
DEST.DT_END,
DEST.DT_REGUPDATE,
DEST.DT_DELETE,
DEST.DT_CARGA
) 
THEN
UPDATE
SET 
DEST.DS_PROMOTION	= UPD.DS_PROMOTION,
DEST.RL_DISCOUNT	= UPD.RL_DISCOUNT,
DEST.DS_TYPE		= UPD.DS_TYPE,
DEST.NR_MINQT		= UPD.NR_MINQT,
DEST.NR_MAXQT		= UPD.NR_MAXQT,
DEST.DT_START		= UPD.DT_START,
DEST.DT_END			= UPD.DT_END,
DEST.DT_REGUPDATE	= UPD.DT_REGUPDATE,
DEST.DT_UPDATE		= GETDATE(),
DEST.DT_DELETE		= UPD.DT_DELETE,
DEST.DT_CARGA		= UPD.DT_CARGA;

SELECT	SPECIALOFFERID					NK_PROMOTION
FROM	SALES.SPECIALOFFER SO
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)


UPDATE		DEST
SET			DEST.DT_DELETE = GETDATE()
FROM		DW_ADVWORKS.SALES.DM_PROMOTION DEST
LEFT JOIN	STG_ADVWORKS.SALES.DEL_DM_PROMOTION DEL ON DEL.NK_PROMOTION = DEST.NK_PROMOTION
WHERE		DEL.NK_PROMOTION IS NULL
AND			DEST.DT_DELETE IS NULL;

DROP TABLE STG_ADVWORKS.SALES.DEL_DM_PROMOTION