USE DW_ADVWORKS;
DROP TABLE SALES.DM_SALESPERSON
USE STG_ADVWORKS;
DROP TABLE SALES.DM_SALESPERSON

USE STG_ADVWORKS;
CREATE TABLE SALES.DM_SALESPERSON (
    NK_SALESPERSON INT NOT NULL,
    DS_FIRSTNAME NVARCHAR(255) NOT NULL,
    DS_LASTNAME NVARCHAR(255) NOT NULL,
    DS_EMAIL NVARCHAR(255) NOT NULL,
    DT_REGUPDATE_BE DATETIME NOT NULL,
    DT_REGUPDATE_SP DATETIME NOT NULL,
    DT_REGUPDATE_P DATETIME NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

IF EXISTS (SELECT 1 FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'SALES.DEL_DM_SALESPERSON') 
           AND [TYPE] IN (N'U'))
BEGIN
   DROP TABLE SALES.DEL_DM_SALESPERSON;
END

CREATE TABLE SALES.DEL_DM_SALESPERSON (
				NK_SALESPERSON INT NOT NULL
)

USE DW_ADVWORKS;
CREATE TABLE SALES.DM_SALESPERSON (
    SK_SALESPERSON NUMERIC(10) IDENTITY(1,1) NOT NULL,
    NK_SALESPERSON INT NOT NULL,
    DS_FIRSTNAME NVARCHAR(255) NOT NULL,
    DS_LASTNAME NVARCHAR(255) NOT NULL,
    DS_EMAIL NVARCHAR(255) NOT NULL,
    DT_REGUPDATE_BE DATETIME NOT NULL,
    DT_REGUPDATE_SP DATETIME NOT NULL,
    DT_REGUPDATE_P DATETIME NOT NULL,
    DT_UPDATE DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL,
	CONSTRAINT DMSALPPK PRIMARY KEY (SK_SALESPERSON)
);

SELECT 		'-1'	NK_SALESPERSON,
			'NO FIRST NAME'	DS_FIRSTNAME,
			'NO LAST NAME'	DS_LASTNAME,
			'NO EMAIL'	DS_EMAIL,
			GETDATE()	DT_REGUPDATE_BE,
			GETDATE()	DT_REGUPDATE_SP,
			GETDATE()	DT_REGUPDATE_P,
			GETDATE()	DT_CARGA
UNION ALL
SELECT 		BE.BUSINESSENTITYID		NK_SALESPERSON,
			FIRSTNAME				DS_FIRSTNAME,
			LASTNAME				DS_LASTNAME,
			EA.EMAILADDRESS			DS_EMAIL,
			BE.MODIFIEDDATE			DT_REGUPDATE_BE,
			SP.MODIFIEDDATE			DT_REGUPDATE_SP,
			P.MODIFIEDDATE			DT_REGUPDATE_P,
			GETDATE()				DT_CARGA
FROM		PERSON.BUSINESSENTITY BE
LEFT JOIN	SALES.SALESPERSON SP ON BE.BUSINESSENTITYID = SP.BUSINESSENTITYID
LEFT JOIN	PERSON.PERSON P ON BE.BUSINESSENTITYID = P.BUSINESSENTITYID
LEFT JOIN	PERSON.EMAILADDRESS EA ON BE.BUSINESSENTITYID = EA.BUSINESSENTITYID
WHERE		1=1
			AND P.PERSONTYPE = 'SP'
--			AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

MERGE DW_ADVWORKS.SALES.DM_SALESPERSON DEST
USING STG_ADVWORKS.SALES.DM_SALESPERSON UPD ON UPD.NK_SALESPERSON = DEST.NK_SALESPERSON
WHEN NOT MATCHED THEN INSERT
VALUES (
UPD.NK_SALESPERSON,
UPD.DS_FIRSTNAME,
UPD.DS_LASTNAME,
UPD.DS_EMAIL,
UPD.DT_REGUPDATE_BE,
UPD.DT_REGUPDATE_SP,
UPD.DT_REGUPDATE_P,
NULL, --UPD.DT_UPDATE
NULL, --UPD.DT_DELETE
UPD.DT_CARGA
) WHEN MATCHED AND
CONCAT(
UPD.DS_FIRSTNAME,
UPD.DS_LASTNAME,
UPD.DS_EMAIL,
UPD.DT_REGUPDATE_BE,
UPD.DT_REGUPDATE_SP,
UPD.DT_REGUPDATE_P,
UPD.DT_DELETE,
UPD.DT_CARGA
) <>
CONCAT(
DEST.DS_FIRSTNAME,
DEST.DS_LASTNAME,
DEST.DS_EMAIL,
DEST.DT_REGUPDATE_BE,
DEST.DT_REGUPDATE_SP,
DEST.DT_REGUPDATE_P,
DEST.DT_DELETE,
DEST.DT_CARGA
)
THEN
UPDATE
SET 
DEST.DS_FIRSTNAME			= UPD.DS_FIRSTNAME,
DEST.DS_LASTNAME				= UPD.DS_LASTNAME,
DEST.DS_EMAIL				= UPD.DS_EMAIL,
DEST.DT_REGUPDATE_BE			= UPD.DT_REGUPDATE_BE,
DEST.DT_REGUPDATE_SP			= UPD.DT_REGUPDATE_SP,
DEST.DT_REGUPDATE_P			= UPD.DT_REGUPDATE_P,
DEST.DT_UPDATE				= GETDATE(),
DEST.DT_DELETE				= UPD.DT_DELETE,
DEST.DT_CARGA				= UPD.DT_CARGA;

SELECT 		BE.BUSINESSENTITYID NK_SALESPERSON
FROM		PERSON.BUSINESSENTITY BE
LEFT JOIN	SALES.SALESPERSON SP ON BE.BUSINESSENTITYID = SP.BUSINESSENTITYID
LEFT JOIN	PERSON.PERSON P ON BE.BUSINESSENTITYID = P.BUSINESSENTITYID
WHERE		1=1
			AND P.PERSONTYPE = 'SP'


--			AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

UPDATE		DEST
SET			DEST.DT_DELETE = GETDATE()
FROM		DW_ADVWORKS.SALES.DM_SALESPERSON DEST
LEFT JOIN	STG_ADVWORKS.SALES.DEL_DM_SALESPERSON DEL ON DEL.NK_SALESPERSON = DEST.NK_SALESPERSON
WHERE		DEL.NK_SALESPERSON IS NULL
AND			DEST.DT_DELETE IS NULL;

DROP TABLE STG_ADVWORKS.SALES.DEL_DM_SALESPERSON