USE STG_ADVWORKS;

CREATE TABLE SALES.FT_SALES (
    DT_ORDER NUMERIC(8) NOT NULL,
    ID_ORDER INT NOT NULL,
    NK_PRODUCT INT NOT NULL,
    NK_PROMOTION INT NOT NULL,
    NK_SUBCATEGORY INT NOT NULL, 
    NK_CUSTOMER INT NOT NULL, 
    NK_ADDRESS INT NOT NULL, 
    NK_SALESPERSON INT,
    NR_QTY INT NOT NULL,
    VL_PRICE DECIMAL(18, 2) NOT NULL, 
    RL_DISCOUNT DECIMAL(18, 2) NOT NULL,
    VL_PD_TOTAL DECIMAL(18, 2) NOT NULL,
    VL_SUBTOTAL DECIMAL(18, 2) NOT NULL, 
    VL_TAX DECIMAL(18, 2) NOT NULL, 
    VL_FREIGHT DECIMAL(18, 2) NOT NULL, 
    VL_TOTAL DECIMAL(18, 2) NOT NULL,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

USE DW_ADVWORKS;
CREATE TABLE SALES.FT_SALES (
	SK_SALES NUMERIC(10) IDENTITY(1,1) NOT NULL ,
    DT_ORDER NUMERIC(8) NOT NULL,
    ID_ORDER INT NOT NULL,
    SK_PRODUCT INT NOT NULL,
    SK_PROMOTION INT NOT NULL,
    SK_SUBCATEGORY INT NOT NULL, 
    SK_CUSTOMER INT NOT NULL, 
    SK_ADDRESS INT NOT NULL, 
    SK_SALESPERSON INT,
    NR_QTY INT NOT NULL,
    VL_PRICE DECIMAL(18, 2) NOT NULL, 
    RL_DISCOUNT DECIMAL(18, 2) NOT NULL,
    VL_PD_TOTAL DECIMAL(18, 2) NOT NULL,
    VL_SUBTOTAL DECIMAL(18, 2) NOT NULL, 
    VL_TAX DECIMAL(18, 2) NOT NULL, 
    VL_FREIGHT DECIMAL(18, 2) NOT NULL, 
    VL_TOTAL DECIMAL(18, 2) NOT NULL,
	DT_UPDATE DATETIME,
    DT_DELETE DATETIME,
    DT_CARGA DATETIME NOT NULL
);

SELECT	CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,SOH.ORDERDATE	)),':-/ ','____'),'_','')) DT_ORDER,
		CONCAT(SOH.SALESORDERID, SOD.PRODUCTID) ID_ORDER,
		iif(SOD.PRODUCTID is null,-1, SOD.PRODUCTID) NK_PRODUCT,
		iif(SOD.SPECIALOFFERID is null,-1, SOD.SPECIALOFFERID) NK_PROMOTION,
		iif(P.PRODUCTSUBCATEGORYID is null,-1, P.PRODUCTSUBCATEGORYID) NK_SUBCATEGORY,
		iif(SOH.CUSTOMERID is null,-1, SOH.CUSTOMERID) NK_CUSTOMER,
		iif(SOH.SHIPTOADDRESSID is null,-1, SOH.SHIPTOADDRESSID) NK_ADDRESS,
		iif(SOH.SALESPERSONID is null,-1, SOH.SALESPERSONID) NK_SALESPERSON,
		iif(SOD.ORDERQTY is null,-1, SOD.ORDERQTY) NR_QTY,
		SOD.UNITPRICE			VL_PRICE,
		SOD.UNITPRICEDISCOUNT	RL_DISCOUNT,
		SOD.LINETOTAL			VL_PD_TOTAL,
		SOH.SUBTOTAL			VL_SUBTOTAL,
		SOH.TAXAMT				VL_TAX,
		SOH.FREIGHT				VL_FREIGHT,
		SOH.TOTALDUE			VL_TOTAL,
		GETDATE()				DT_CARGA
FROM	SALES.SALESORDERHEADER SOH
		LEFT JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
		LEFT JOIN SALES.CUSTOMER C ON SOH.CUSTOMERID = C.CUSTOMERID
		LEFT JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
		LEFT JOIN PRODUCTION.PRODUCTSUBCATEGORY PS ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTSUBCATEGORYID

WITH UPD AS (
SELECT	DT_ORDER,
		ID_ORDER,
		SK_PRODUCT,
		SK_PROMOTION,
		SK_SUBCATEGORY,
		SK_CUSTOMER,
		SK_ADDRESS,
		SK_SALESPERSON,
		VL_PRICE,
		S.RL_DISCOUNT,
		VL_PD_TOTAL,
		VL_SUBTOTAL,
		VL_TAX,
		VL_FREIGHT,
		VL_TOTAL,
		NR_QTY,
		NULL DT_UPDATE,
		NULL DT_DELETE,
		S.DT_CARGA
FROM	STG_ADVWORKS.SALES.FT_SALES S
		LEFT JOIN DW_ADVWORKS.SALES.DM_PRODUCT P ON P.NK_PRODUCT = S.NK_PRODUCT
		LEFT JOIN DW_ADVWORKS.SALES.DM_PROMOTION P2 ON P2.NK_PROMOTION = S.NK_PROMOTION
		LEFT JOIN DW_ADVWORKS.SALES.DM_PRODUCT_CATEGORY PC ON PC.NK_SUBCATEGORY = S.NK_SUBCATEGORY 
		LEFT JOIN DW_ADVWORKS.SALES.DM_CUSTOMER C ON C.NK_CUSTOMER = S.NK_CUSTOMER
		LEFT JOIN DW_ADVWORKS.SALES.DM_ADDRESS A ON A.NK_ADDRESS = S.NK_ADDRESS
		LEFT JOIN DW_ADVWORKS.SALES.DM_SALESPERSON SP ON SP.NK_SALESPERSON = S.NK_SALESPERSON
)

MERGE INTO DW_ADVWORKS.SALES.FT_SALES DEST
USING UPD ON DEST.ID_ORDER = UPD.ID_ORDER
WHEN NOT MATCHED THEN INSERT values (
UPD.DT_ORDER,
UPD.ID_ORDER,
UPD.SK_PRODUCT,
UPD.SK_PROMOTION,
UPD.SK_SUBCATEGORY,
UPD.SK_CUSTOMER,
UPD.SK_ADDRESS,
UPD.SK_SALESPERSON,
UPD.VL_PRICE,
UPD.RL_DISCOUNT,
UPD.VL_PD_TOTAL,
UPD.VL_SUBTOTAL,
UPD.VL_TAX,
UPD.VL_FREIGHT,
UPD.VL_TOTAL,
UPD.NR_QTY,
NULL,
NULL,
UPD.DT_CARGA)
WHEN MATCHED AND
CONCAT(
DEST.VL_PD_TOTAL,
DEST.VL_SUBTOTAL,
DEST.VL_TAX,
DEST.VL_FREIGHT,
DEST.VL_TOTAL,
DEST.NR_QTY,
DEST.DT_UPDATE,
DEST.DT_DELETE,
DEST.DT_CARGA
) 
<> CONCAT(
UPD.VL_PD_TOTAL,
UPD.VL_SUBTOTAL,
UPD.VL_TAX,
UPD.VL_FREIGHT,
UPD.VL_TOTAL,
UPD.NR_QTY,
UPD.DT_UPDATE,
UPD.DT_DELETE,
UPD.DT_CARGA
)
THEN
UPDATE SET 
DEST.VL_PD_TOTAL					= UPD.VL_PD_TOTAL,	
DEST.VL_SUBTOTAL					= UPD.VL_SUBTOTAL,	
DEST.VL_TAX							= UPD.VL_TAX,		
DEST.VL_FREIGHT						= UPD.VL_FREIGHT,	
DEST.VL_TOTAL						= UPD.VL_TOTAL,	
DEST.NR_QTY							= UPD.NR_QTY,		
DEST.DT_UPDATE						= GETDATE(),
DEST.DT_DELETE						= UPD.DT_DELETE,	
DEST.DT_CARGA						= UPD.DT_CARGA;