--USE ADVENTUREWORKS2019

--FT_SALES
SELECT	CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,SOH.ORDERDATE	)),':-/ ','____'),'_','')) DT_ORDER,
		SOH.SALESORDERID		ID_ORDER,
		SOD.PRODUCTID			ID_PRODUCT,
		SOD.SPECIALOFFERID		ID_PROMOTION,
		PS.PRODUCTCATEGORYID	ID_CATEGORY,
		P.PRODUCTSUBCATEGORYID	ID_SUBCATEGORY,
		SOH.CUSTOMERID			ID_CUSTOMER,
		SOH.SALESPERSONID		ID_SALESP,
		SOD.ORDERQTY			NR_QTY,
		SOD.UNITPRICE			VL_PRICE,
		SOD.UNITPRICEDISCOUNT	RL_DISCOUNT,
		SOD.LINETOTAL			VL_PD_TOTAL,
		SOH.SUBTOTAL			VL_SUBTOTAL,
		SOH.TAXAMT				VL_TAX,
		SOH.FREIGHT				VL_FREIGHT,
		SOH.TOTALDUE			VL_TOTAL
FROM	SALES.SALESORDERHEADER SOH
		LEFT JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID
		LEFT JOIN SALES.CUSTOMER C ON SOH.CUSTOMERID = C.CUSTOMERID
		LEFT JOIN PRODUCTION.PRODUCT P ON SOD.PRODUCTID = P.PRODUCTID
		LEFT JOIN PRODUCTION.PRODUCTSUBCATEGORY PS ON P.PRODUCTSUBCATEGORYID = PS.PRODUCTSUBCATEGORYID

SELECT * FROM SALES.Store
ORDER BY 3
SELECT * FROM SALES.SALESORDERHEADER SOH
		JOIN SALES.SALESORDERDETAIL SOD ON SOH.SALESORDERID = SOD.SALESORDERID

SELECT MAX(STOREID) FROM SALES.Customer
SELECT MAX(A.BUSINESSENTITYID) FROM SALES.STORE A
SELEC
SELECT * FROM PERSON.BusinessEntity

--DM_PROMOTION
SELECT	SPECIALOFFERID					NK_PROMOTION,
		DESCRIPTION						DS_PROMOTION,
		DISCOUNTPCT						RL_DISCOUNT,
		TYPE							DS_TYPE,
		MINQTY							NR_MINQT,
		IIF(MAXQTY IS NULL, 0, MAXQTY)	NR_MAXQT,
		MODIFIEDDATE					DT_REGUPDATE,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,STARTDATE)),':-/ ','____'),'_','')) DT_START,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,ENDDATE)),':-/ ','____'),'_',''))	DT_END,
		GETDATE()						DT_CARGA
FROM	SALES.SPECIALOFFER SO

--DM_PRODUCT
SELECT	P.PRODUCTID				NK_PRODUCT,
		P.NAME					DS_PRODUCT,
		CASE WHEN P.COLOR IS NOT NULL THEN P.COLOR ELSE CASE WHEN P.NAME LIKE '% BLUE%' THEN 'BLUE' ELSE CASE WHEN P.NAME LIKE '% RED%' THEN 'RED' ELSE CASE WHEN P.NAME LIKE '% SILVER%' THEN 'SILVER' ELSE CASE WHEN P.NAME LIKE '% YELLOW%' THEN 'YELLOW' ELSE CASE WHEN P.NAME LIKE '% BLACK%' THEN 'BLACK' ELSE 'STANDARD' END END END END END END DS_COLOR,
		P.STANDARDCOST			VL_STDCOST,
		P.LISTPRICE				VL_SLGPRICE,
		CASE WHEN P.SIZE IS NULL THEN 'STANDARD' ELSE P.SIZE END DS_SIZE,
		P.DAYSTOMANUFACTURE		NR_DAYSMANUFACTURE,
		CASE WHEN P.PRODUCTLINE IS NOT NULL THEN P.PRODUCTLINE ELSE CASE WHEN P.PRODUCTLINE = 'R' THEN 'ROAD' ELSE CASE WHEN P.PRODUCTLINE = 'M' THEN 'MOUNTAIN'	ELSE CASE WHEN P.PRODUCTLINE = 'T' THEN 'TOURING' ELSE 'STANDARD' END END END END DS_PRODUCTLINE,
		CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,SELLSTARTDATE)),':-/ ','____'),'_',''))			DT_SELLSTART,
		CASE WHEN SELLENDDATE IS NULL THEN -1 ELSE CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,SELLENDDATE)),':-/ ','____'),'_','')) END DT_SELLEND,
		CASE WHEN DISCONTINUEDDATE IS NULL THEN -1 ELSE CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,DISCONTINUEDDATE)),':-/ ','____'),'_','')) END DT_DISCONTINUED,
		P.MODIFIEDDATE			DT_REGUPDATE,
		GETDATE()				DT_CARGA
FROM	PRODUCTION.PRODUCT P
WHERE	1=1
--		AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

--DM_PRODUCT_CATEGORY
SELECT	PS.PRODUCTSUBCATEGORYID	ID_SUBCATEGORY,
		PS.NAME					DS_SUBCATEGORY,
		PC.PRODUCTCATEGORYID	ID_CATEGORY,
		PC.NAME					DS_CATEGORY,
		PS.MODIFIEDDATE			DT_REGUPDATE,
		PC.MODIFIEDDATE			DT_REGUPDATE,
		GETDATE()				DT_CARGA
FROM	PRODUCTION.PRODUCTSUBCATEGORY PS
		LEFT JOIN PRODUCTION.PRODUCTCATEGORY PC ON PS.PRODUCTCATEGORYID = PC.PRODUCTCATEGORYID

USE ADVENTUREWORKS2019
SELECT * FROM PRODUCTION.PRODUCTSUBCATEGORY
WHERE PRODUCTID = 749


--DM_BUSINESS_ENTITY
/*SELECT 	P.BUSINESSENTITYID		ID_CUSTOMER,
		P.PERSONTYPE			DS_CUSTOMERTYPE,
		P.FIRSTNAME				DS_NAME,
		FIRSTNAME				DS_FIRSTNAME,
		LASTNAME				DS_LASTNAME,
		EA.EMAILADDRESS			DS_EMAIL,
		PP.PHONENUMBER			NR_PHONE,
		A.ADDRESSLINE1			DS_ADRESS,
		A.CITY					DS_CITY,
		SP.NAME					DS_STATE,
		SP.COUNTRYREGIONCODE	DS_COUNTRY,
		A.POSTALCODE			NR_POSTALCODE,
		ST.NAME					DS_TERRITORY
FROM	SALES.CUSTOMER C
		LEFT JOIN PERSON.PERSON P ON C.CUSTOMERID = P.BUSINESSENTITYID
		LEFT JOIN PERSON.BUSINESSENTITYADDRESS BEA ON P.BUSINESSENTITYID = BEA.BUSINESSENTITYID
		LEFT JOIN PERSON.ADDRESS A ON BEA.ADDRESSID = A.ADDRESSID
		LEFT JOIN PERSON.STATEPROVINCE SP ON A.STATEPROVINCEID = SP.STATEPROVINCEID
		LEFT JOIN SALES.SALESTERRITORY ST ON SP.TERRITORYID = ST.TERRITORYID
		LEFT JOIN PERSON.EMAILADDRESS EA ON P.BUSINESSENTITYID = EA.BUSINESSENTITYID
		LEFT JOIN PERSON.PERSONPHONE PP ON P.BUSINESSENTITYID = PP.BUSINESSENTITYID
*/

--DM_SALESPERSON
SELECT 		BE.BUSINESSENTITYID		NK_SALESPERSON,
			FIRSTNAME				DS_FIRSTNAME,
			LASTNAME				DS_LASTNAME,
			EA.EMAILADDRESS			DS_EMAIL,
			PP.PHONENUMBER			NR_PHONE,
			BE.MODIFIEDDATE			DT_REGUPDATE_BE,
			SP.MODIFIEDDATE			DT_REGUPDATE_SP,
			P.MODIFIEDDATE			DT_REGUPDATE_P,
			BEA.MODIFIEDDATE		DT_REGUPDATE_BEA,
			EA.MODIFIEDDATE			DT_REGUPDATE_EA,
			PP.MODIFIEDDATE			DT_REGUPDATE_PP
FROM		PERSON.BUSINESSENTITY BE
LEFT JOIN	SALES.SALESPERSON SP ON BE.BUSINESSENTITYID = SP.BUSINESSENTITYID
LEFT JOIN	PERSON.PERSON P ON BE.BUSINESSENTITYID = P.BUSINESSENTITYID
LEFT JOIN	PERSON.BUSINESSENTITYADDRESS BEA ON BE.BUSINESSENTITYID = BEA.BUSINESSENTITYID
LEFT JOIN	PERSON.EMAILADDRESS EA ON BE.BUSINESSENTITYID = EA.BUSINESSENTITYID
LEFT JOIN	PERSON.PERSONPHONE PP ON BE.BUSINESSENTITYID = PP.BUSINESSENTITYID
WHERE		1=1
			AND P.PERSONTYPE = 'SP'
--			AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

--DM_SALESPERSON
SELECT 		BE.BUSINESSENTITYID		NK_SALESPERSON,
			FIRSTNAME				DS_FIRSTNAME,
			LASTNAME				DS_LASTNAME,
			EA.EMAILADDRESS			DS_EMAIL,
			PP.PHONENUMBER			NR_PHONE,
			BE.MODIFIEDDATE			DT_REGUPDATE_BE,
			SP.MODIFIEDDATE			DT_REGUPDATE_SP,
			P.MODIFIEDDATE			DT_REGUPDATE_P,
			BEA.MODIFIEDDATE		DT_REGUPDATE_BEA,
			EA.MODIFIEDDATE			DT_REGUPDATE_EA,
			PP.MODIFIEDDATE			DT_REGUPDATE_PP
FROM		PERSON.BUSINESSENTITY BE
LEFT JOIN	SALES.SALESPERSON SP ON BE.BUSINESSENTITYID = SP.BUSINESSENTITYID
LEFT JOIN	PERSON.PERSON P ON BE.BUSINESSENTITYID = P.BUSINESSENTITYID
LEFT JOIN	PERSON.BUSINESSENTITYADDRESS BEA ON BE.BUSINESSENTITYID = BEA.BUSINESSENTITYID
LEFT JOIN	PERSON.EMAILADDRESS EA ON BE.BUSINESSENTITYID = EA.BUSINESSENTITYID
LEFT JOIN	PERSON.PERSONPHONE PP ON BE.BUSINESSENTITYID = PP.BUSINESSENTITYID
WHERE		1=1
			AND P.PERSONTYPE = 'SP'
--			AND	CONVERT(DATE,MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

--DM_CUSTOMER
WITH Customer AS (
SELECT C.CustomerID, IIF(C.PERSONID IS NULL, C.STOREID, C.PERSONID) BusinessEntityID, c.MODIFIEDDATE FROM SALES.Customer C
)

SELECT 		BE.BUSINESSENTITYID		NK_SALESPERSON,
			FIRSTNAME				DS_FIRSTNAME,
			LASTNAME				DS_LASTNAME,
			BE.MODIFIEDDATE			DT_REGUPDATE_BE,			
			C.MODIFIEDDATE			DT_REGUPDATE_P,
			BE.MODIFIEDDATE		DT_REGUPDATE_BEA,
			P.MODIFIEDDATE			DT_REGUPDATE_EA,
			GETDATE()				DT_CARGA
FROM		Customer C
JOIN		PERSON.BUSINESSENTITY BE ON C.BusinessEntityID = BE.BusinessEntityID
LEFT JOIN	PERSON.Person P ON C.BusinessEntityID = P.BusinessEntityID
LEFT JOIN	SALES.Store S ON C.BusinessEntityID = S.BusinessEntityID 
WHERE		1=1
--			AND	CONVERT(DATE,C.MODIFIEDDATE) >= CONVERT(DATE,GETDATE()-7)

--DM_ADDRESS
SELECT	ADDRESSID			NK_ADDRESS, 
		ADDRESSLINE1		DS_ADDRESS1, 
		CITY				DS_CITY, 
		SP.NAME				DS_STATE,
		STATEPROVINCECODE	SG_STATE, 
		CountryRegionCode	DS_COUNTRY,
		A.ModifiedDate		DT_UPDATE_A,
		SP.ModifiedDate		DT_UPDATE_SP,
		GETDATE()			DT_CARGA
FROM	PERSON.ADDRESS A
		LEFT JOIN PERSON.STATEPROVINCE SP ON A.STATEPROVINCEID = SP.STATEPROVINCEID

--DM_TIME
SELECT	CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,DATE)),':-/ ','____'),'_','')) ID_DATE,
		DATE					DT_DATE,
		YEAR(DATE)				NR_YEAR,
		DATEPART(QUARTER, DATE) NR_QUARTER,
		MONTH(DATE)				NR_MONTH,
		DAY(DATE)				NR_DAY,
		DATEPART(WEEKDAY, DATE)	NR_DAYOFWEEK,
		DATENAME(WEEKDAY, DATE) DS_DAY,
		DATENAME(MONTH, DATE)	DS_MONTH
FROM	(SELECT
		DATEADD(DAY, NUMBER, '2010-01-01') AS DATE
		FROM
		MASTER.DBO.SPT_VALUES
		WHERE
		TYPE = 'P' AND NUMBER <= DATEDIFF(DAY, '2010-01-01', '2015-12-31')) DATERANGE


SELECT
    CONVERT(NUMERIC(8),REPLACE(TRANSLATE(CONVERT(VARCHAR(10),CONVERT(DATE,DATE)),':-/ ','____'),'_','')) AS NK_DATE,
    DATE AS DT_DATE,
    YEAR(DATE) AS NR_YEAR,
    DATEPART(QUARTER, DATE) AS NR_QUARTER,
    MONTH(DATE) AS NR_MONTH,
    DAY(DATE) AS NR_DAY,
    DATEPART(WEEKDAY, DATE) AS NR_DAYOFWEEK,
    DATENAME(WEEKDAY, DATE) AS DS_DAY,
    DATENAME(MONTH, DATE) AS DS_MONTH
FROM (
    SELECT
        DATEADD(DAY, NUMBER, '2010-01-01') AS DATE
    FROM
        MASTER.DBO.SPT_VALUES
    WHERE
        TYPE = 'P' AND NUMBER <= DATEDIFF(DAY, '2010-01-01', '2015-12-31')
) AS DATERANGE